## -- location: /etc/ssh/sshd_config.d/zba.conf

Port 22
#AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

## AuthorizedKeysFile	.ssh/authorized_keys

# To disable tunneled clear text passwords, change to no here!
## PasswordAuthentication yes

X11Forwarding yes 
X11UseLocalhost yes 

# override default of no subsystems
## Subsystem	sftp	/usr/lib/ssh/sftp-server
#	ForceCommand cvs server
