# Include drop-in configurations
## Include /etc/ssh/sshd_config.d/*.conf

Port 3512
#AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

X11Forwarding yes 
X11DisplayOffset 0
X11UseLocalhost yes 

MaxSessions 20
# -------------- 
# depracted setting !!! (RSAAuthentication yes)
PubkeyAuthentication yes

AllowUsers qi
AllowGroups qi tester

Match User qi
	PasswordAuthentication no
# --------------
