# location: /etc/nginx/conf.d
# must have 'include /etc/nginx/conf.d/*.conf;' in http { ... } at etc/nginx/nginx.conf
server {
    listen      443 http2 ssl proxy_protocol;
    listen      [::]:443 http2 ssl proxy_protocol;
    root        /var/www/html;
    charset     utf-8;
    server_name quebit.top;
    index       index.html index.php;

    ssl_certificate     /etc/nginx/quebit.top/fullchain.cer;
    ssl_certificate_key /etc/nginx/quebit.top/quebit.top.key;

    real_ip_header proxy_protocol;
    error_page 497 https://$http_host$request_uri; # http error code:497 transmit to https request

    # empty UA is forbidden
    if ($http_user_agent ~ ^$){
        return 444;
    }
    # deny some crawler websites, allow curl
    if ($http_user_agent ~* "Scrapy|python|Nmap|wget|httpclient|MJ12bot|Expanse|ahrefsbot|seznambot|serpstatbot|sindresorhus|zgrab"){
        return 444;
    }

    location / {
        set $real_ip $proxy_protocol_addr;
    }

    location /alist/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:5244;
        client_max_body_size 10240m;
    }

    location /qbt/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:8028/;
    }

    location ~ \.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$; 
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        include fastcgi_params; 
    }

    location /filesrv/ {
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        add_after_body /autoindex.html;
        try_files $uri $uri/ =404;
    }

    location /favicon.ico {
        alias /var/www/mmm.ico;
    }
    error_page  404              /404.html;
    error_page  500 502 503 504  /50x.html;
}

server {
    listen      80;
    listen      [::]:80;
    root        /var/www/html;
    charset     utf-8;
    index       index.html index.php;
    real_ip_header X-Forwarded-For; # recv frps nginx real IP

    if ($http_user_agent ~ ^$){
        return 444;
    }
    if ($http_user_agent ~* "Scrapy|python|Nmap|wget|httpclient|MJ12bot|Expanse|ahrefsbot|seznambot|serpstatbot|sindresorhus|zgrab"){
        return 444;
    }

    location / {
        try_files $uri $uri/ /index.php;
    }
 
    location /alist/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:5244;
        # the max size of file to upload
        client_max_body_size 10240m;
    }

    location /qbt/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:8028/;
    }

    location ~ \.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$; 
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location /filesrv/ {
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        add_after_body /autoindex.html;
        try_files $uri $uri/ =404;
    }

    location /favicon.ico {
        root /var/www;
    }

    error_page  404              /404.html;
    error_page  500 502 503 504  /50x.html;
}

