# location: /etc/nginx/conf.d
# must have 'include /etc/nginx/conf.d/*.conf;' in http at etc/nginx/nginx.conf
server {
    listen      80;
    charset     utf-8;
    root        /var/www/html;

    server_name hpnu.cn;

    #access_log  logs/host.access.log  main;

    location / {
        index  index.html index.php index.htm;
    }

    location ~ \.php$ {
        try_files $uri = 404;
        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini # 
        # With php5-cgi alone: #    fastcgi_pass 127.0.0.1:9000; #    # With php5-fpm:
        fastcgi_split_path_info ^(.+\.php)(/.+)$; 
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        #fastcgi_param HTTPS off;
        include fastcgi_params; 
    }
    #error_page  404              /404.html;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /var/www/html;
    }
}

