# -- fix the conf of ubuntu20.04
# -- location: /etc

user root;
worker_processes auto;
pid /run/nginx.pid;
# include /etc/nginx/modules-enabled/*.conf;

events {
    accept_mutex on;
    use epoll;
    worker_connections  1024;
    multi_accept on;
}

http {
    #### Basic Settings

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    keepalive_requests 8192;
    server_tokens off;
    # server_names_hash_bucket_size 64;
    # server_name_in_redirect off;

    types_hash_max_size 3096;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    #### SSL Settings

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_session_timeout 5m;

    #### Logging Settings

    # underscores_in_headers on;
    log_format main '$remote_addr $proxy_protocol_addr [$time_iso8601] "$request" '
                    '$status "$http_user_agent" $body_bytes_sent '
                    '"$http_referer" "$http_x_forwarded_for" $remote_user';
    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log;

    #### Gzip Settings

    gzip  on;
    gzip_min_length 1k;
    # gzip_vary on;
    # gzip_proxied any;
    # gzip_comp_level 6;
    # gzip_buffers 16 8k;
    # gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    #### Virtual Host Configs

    include /etc/nginx/conf.d/*.conf;
}
